FROM nginx

WORKDIR /app

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./server/ .

RUN apt update -y && \
apt install -y gcc libfcgi-dev spawn-fcgi && \
chmod +x ./entrypoint.sh

CMD [ "./entrypoint.sh" ]